---
task-defaults:
  #optimization:
  #  skip-unless-changed:
  #    - sitePostProcess.py
  #    - site/**
  #    # Copy the process kinds list so that we always run if a process task runs.
  #    - processes.json
  #    - generate.py
  #    - crashes.py
  worker-type: b-linux
  worker:
    docker-image: {in-tree: linux}
    max-run-time: 1800

tasks:
  site:
    name: deploy-site
    description: "Deploy the crash ping website."
    scopes:
      - secrets:get:project/mozilla/process-top-crashes/ci
    soft-dependencies:
      - process-pings
    run:
      using: run-task
      cache-dotcache: true
      cwd: '{checkout}'
      command:
        - bash
        - -euo
        - pipefail
        - -c
        - >
          SECRETS=$(curl -sSLf http://taskcluster/secrets/v1/secret/project/mozilla/process-top-crashes/ci);
          NETLIFY_TOKEN=$(echo $SECRETS | jq -r .secret.netlify.token);
          NETLIFY_SITE_ID=$(echo $SECRETS | jq -r .secret.netlify.site_id);

          curl -sSLf http://taskcluster/index/v1/task/mozilla.v2.process-top-crashes.latest.process-pings/artifacts/public/processed.tar.gz | tar -xzf -;
          python3 sitePostProcess.py;
          (cd site; zip -r ../site.zip .);
          curl -H "Content-Type: application/zip" -H "Authorization: Bearer $NETLIFY_TOKEN" --data-binary "@site.zip" https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys;
