---
task-defaults:
  worker-type: t-linux-large
  worker:
    docker-image: {in-tree: linux}
    max-run-time: 36000
    artifacts:
      - type: directory
        name: "public/dist"
        path: "/builds/worker/checkouts/src/_dist"

tasks:
  build:
    name: dashboard-build
    description: "Build the dashboard website."
    run:
      using: run-task
      cache-dotcache: true
      cwd: '{checkout}'
      command:
        - bash
        - -cx
        - python3 generate.py
