---
task-defaults:
  worker-type: t-linux-large
  worker:
    docker-image: {in-tree: linux}
    max-run-time: 36000
    artifacts:
      - type: directory
        name: "public/dist"
        path: "/builds/worker/checkouts/vcs/_dist"

tasks:
  build:
    name: dashboard-build
    description: "Build the dashboard website."
    scopes:
      - secrets:get:project/mozilla/process-top-crashes/ci
    run:
      using: run-task
      cache-dotcache: true
      cwd: '{checkout}'
      command:
        - bash
        - -euo
        - pipefail
        - -c
        - >
          SECRETS=$(curl http://taskcluster/secrets/v1/secret/project/mozilla/process-top-crashes/ci);
          export REDASH_API_KEY=$(echo $SECRETS | jq -r .secret.redash_api_key);
          NETLIFY_TOKEN=$(echo $SECRETS | jq -r .secret.netlify.token);
          NETLIFY_SITE_ID=$(echo $SECRETS | jq -r .secret.netlify.site_id);
          python3 generate.py;
          (cd _dist; zip -r ../site.zip .);
          curl -H "Content-Type: application/zip" -H "Authorization: Bearer $NETLIFY_TOKEN" --data-binary "@site.zip" https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys;
