---
task-defaults:
  #optimization:
  #  skip-unless-changed:
  #    - sitePostProcess.py
  #    - site/**
  #    # Copy the process kinds list so that we always run if a process task runs.
  #    - processes.json
  #    - generate.py
  #    - crashes.py
  run-on-git-branches:
    - main
  run-on-tasks-for:
    - cron
    - github-push
  worker-type: b-linux
  worker:
    docker-image: {in-tree: linux}
    max-run-time: 1800

tasks:
  site:
    name: deploy-site
    description: "Deploy the crash ping website."
    scopes:
      - secrets:get:project/mozilla/process-top-crashes/ci
    soft-dependencies:
      - process-pings
    run:
      using: run-task
      cache-dotcache: true
      cwd: '{checkout}'
      command:
        - bash
        - -euo
        - pipefail
        - -c
        - >
          SECRETS=$(curl -sSLf http://taskcluster/secrets/v1/secret/project/mozilla/process-top-crashes/ci);
          export NETLIFY_AUTH_TOKEN=$(echo $SECRETS | jq -r .secret.netlify.token);
          export NETLIFY_SITE_ID=$(echo $SECRETS | jq -r .secret.netlify.site_id);

          curl -sSLf https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/mozilla.v2.process-top-crashes.latest.process-pings/artifacts/public/processed.tar.gz | tar -xzf -;
          python3 sitePostProcess.py;
          netlify deploy --prod;
